### ISSUE TITLE
Only question deodex android P.

### ISSUE THREAD

**Issue by ale8530** [anestisb/vdexExtractor#25]
Thank you for today's update for android P, but I wanted to ask you for information, launching the command "./vdexExtractor -i Apk.vdex" I have output **Apk_classes.cdex**, is it possible to have **Apk_classes.dex** as android 8.x?

**Comment by anestisb** [comment]
Converting a CompactDex file back to a standard Dex file is still a work in progress (see https://github.com/anestisb/vdexExtractor/issues/23).

The primary purpose I've started this project was to have the primitives to parse, disassemble and decompile (unquicken) the Vdex containers mostly for research purposes. However, a few days after its release it has been picked-up by ROM devs & other individuals that were de-odexing resources from factory images to repack them in their images. That was a nice turnover since more people used the tool and reported bugs/suggestions/improvements, that lead towards improving it. However, the primary focus of the tool hasn't change, thus a de-odexing orientation is not my number one priority at the time being.

Now since Google is doing a poor job to maintain & expand my contributions to upstream oatdump regarding unquickening optimized bytecode assets, and since I'm also maintaining and needing the [android-prepare-vendor](https://github.com/anestisb/android-prepare-vendor) project for other tasks, I need to improvise again. Hopefully, I'll have something solid within the next couple of days.

Despite being a duplicate, let's leave this issue a few days open since I'm guessing that similar questions will surface the next hours.

**Comment by ale8530** [comment]
Thank you you were very kind to respond, then wait calmly, I thought it was ready :)

**Comment by anestisb** [comment]
As explained in https://github.com/anestisb/vdexExtractor/issues/23 a Cdex converter tool and the required deodex automation has been pushed in the project. So closing this.
