### ISSUE TITLE
 (Question) Can it be a conversion problem from .cdex to .dex?

### ISSUE THREAD

**Issue by ale8530** [anestisb/vdexExtractor#28]
I was able to complete a deodex with Android 9, but I had a strange problem, which I'm trying to understand, basically to get the device up and running the following files:

framework/arm
framework/arm64
framework/oat
framework/*.vdex

I can not figure out if this problem is due to the conversion from .cdex to .dex or maybe it's the new .rel files?

As a premise the script I use works perfectly on android 8.x so I exclude a script problem

**Comment by anestisb** [comment]
I don't understand what exactly is the question? If you have a specific file that you suspect is not decompiled or converted to StandardDex properly, I can have a look if you upload it somewhere. Otherwise I can't really help.

I've used decompiled & converted files in other projects I'm working on and so far I haven't noticed any issues.

**Comment by ale8530** [comment]
I close it is probably an error of my tool thank you for answering
