### ISSUE TITLE
Script request to use deodex command line

### ISSUE THREAD

**Issue by ale8530** [anestisb/vdexExtractor#6]
Meanwhile, I thank the developer of this excellent tool that allows the deodex of Android or very quickly.

I wanted to ask if you could create a script to run the deodex from a specific folder, for example:

I have the folder "system" on my pc launch the command ./deodex.sh and he reads the directories and makes the deodex of that folder.

I know I'm asking a lot, but obviously the trouble will be compensated.

Thank you for your attention

**Comment by anestisb** [comment]
The tool currently supports only 1-level of recursion that is why you can't run against an entire android partition.

However you can copy all vdex files under one directory and run the tool against it.

```bash
$ mkdir vdex_files; find system_dir -name "*.vdex" | while read -r file; do cp "$file" vdex_files/; done
$ vdexExtractor -i vdex_files
``` 

I might consider adding more recursion levels in the tool, although it will have to wait since busy with other things.

**Comment by ale8530** [comment]
very thanks, i try your solution, you have paypal for donation?

**Comment by anestisb** [comment]
Appreciate the gesture. No donation required though.

**Comment by ale8530** [comment]
Very Thanks :)

**Comment by Variusis** [comment]
system\app/SmsExtra/SmsExtra.apk eror deodex
