### ISSUE TITLE
Extract dex from .odex files

### ISSUE THREAD

**Issue by ingbrzy** [anestisb/vdexExtractor#8]
Can you add support for extract .dex from .odex files for Android 6.x/7.x..?

Thank you for your answer..

**Comment by anestisb** [comment]
This tool is processing the new Vdex files that have been introduced in the Oreo release (8.0). Older Android versions are storing the Dex files in the .data section of the Oat file (odex file). I don't plan to add support for older versions since this tool is focusing on Vdex files.

You can use the oatdump utility of the libart (or any of the other third party tools being released) to extract the Dex files from the Oat files.
